language: python

python:
  - 2.7
  - 3.4

before_install:
  - export PYTHONIOENCODING=UTF8
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create -n env-conda --yes "python=$TRAVIS_PYTHON_VERSION"
  - source activate env-conda
  - conda install --yes cython numpy scipy pandas pip
  - pip install -q `cat requirements.txt | grep -v numpy | grep -v scipy | grep -vi cython`
  - pip install -q coveralls nose-cov

# command to run tests
script:
  - python -m unittest -v test.test_tools.TestToolsInstallation
  - nosetests -v --with-xunit --with-coverage --cover-package broad_utils,assembly,interhost,intrahost,ncbi,read_utils,reports,taxon_filter,tools,util --cover-erase --cover-inclusive --cover-branches --cover-tests --nocapture

# post-tests
after_success:
  - coveralls
