language: python
sudo: false

env:
  global:
  - GATK_PATH=bin_bundles/GenomeAnalysisTK-3.3-0-g37228af
  - NOVOALIGN_PATH=bin_bundles/novocraft_v3
  - PYTHONIOENCODING=UTF8
  - secure: l9tLtFKGNhaRdRN2N7Fiks63VatVCOtDUG7FI/pi7JNJu/EriTwDRlncoVCRCJZKOdxG8OrwC1BLX6CNqpVjJISEPGV/djsf2wCV9vi6oa+OsvMymsJAjOYkLezwRLVZp/0l/sGumPGz+q+XIM8VnkOZezIvZjGaaAtBpRTHdmA=

python:
  - 2.7
  - 3.4

install:
  - wget http://www.broadinstitute.org/~dpark/viral_ngs-gatk_novoalign-encrypted_for_travis.tar.gz.enc
  - openssl aes-256-cbc -d -k "$BUNDLE_SECRET" -in viral_ngs-gatk_novoalign-encrypted_for_travis.tar.gz.enc -out bin_bundles.tar.gz
  - tar -xzpvf bin_bundles.tar.gz
  - pip install -r -q requirements.txt
  - pip install -q coveralls nose-cov
  - python -m unittest -v test.test_tools.TestToolsInstallation

script:
  - nosetests -v --with-xunit --with-coverage --cover-package broad_utils,assembly,interhost,intrahost,ncbi,read_utils,reports,taxon_filter,tools,util --cover-erase --cover-inclusive --cover-branches --cover-tests --nocapture

after_success:
  - coveralls
