language: python
sudo: false

cache:
 directories:
  - caches

env:
  global:
  - GATK_PATH=bin_bundles/GenomeAnalysisTK-3.3-0-g37228af
  - NOVOALIGN_PATH=bin_bundles/novocraft_v3
  - PYTHONIOENCODING=UTF8
  - secure: l9tLtFKGNhaRdRN2N7Fiks63VatVCOtDUG7FI/pi7JNJu/EriTwDRlncoVCRCJZKOdxG8OrwC1BLX6CNqpVjJISEPGV/djsf2wCV9vi6oa+OsvMymsJAjOYkLezwRLVZp/0l/sGumPGz+q+XIM8VnkOZezIvZjGaaAtBpRTHdmA=

python:
  - 2.7
  - 3.4

before_install:
  - travis/before_install.sh

install:
  - travis/install-pip.sh
  - travis/install-tools.sh

script:
  - travis/tests-unit.sh
  - travis/tests-long.sh

after_success:
  - coveralls
